version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: devlog_postgres
    restart: always
    environment:
      POSTGRES_DB: devlogdb
      POSTGRES_USER: devlog
      POSTGRES_PASSWORD: devlogpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
