spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/devlog
    username: devlog
    password: devlogpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true