name: DevLog CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: devlog
          POSTGRES_USER: devlog
          POSTGRES_PASSWORD: devlogpass
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U devlog"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/devlogdb
      SPRING_DATASOURCE_USERNAME: devlog
      SPRING_DATASOURCE_PASSWORD: devlogpass

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('backend/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven

    - name: Build and Test
      run: mvn clean verify
      working-directory: backend
